### ISSUE TITLE
I'm impressed by your work!

### ISSUE THREAD

**Issue by Eric-mingjie** [Researchnix/6nimmt-python#2]
That is exellent work!Recently I'm also working on writing an AI for 6nimmit game.I want to ask what method you use in your AI.Was it the MiniMax tree or other method?That would be exetremely helpful.

**Comment by Researchnix** [comment]
Thank you. I have definitely not used the MinMax tree, I barely know what that is. I tried to intuitively implement a function that does what I would give a friend as advice for this game. 
I'll look into other strategies for AI's later this month when I have more time. Feel free to clone this repo to create your own AI, I described "how-to" in the Readme.

**Comment by Eric-mingjie** [comment]
Thanks a lot.
